/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas_banco;

/**
 *
 * @author fvarg
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        btnactividadesrecientes = new javax.swing.JButton();
        btnsaldoactual = new javax.swing.JButton();
        btncomprar = new javax.swing.JButton();
        btninfocuenta = new javax.swing.JButton();
        btntransferir = new javax.swing.JButton();
        anuncios = new javax.swing.JTextField();
        nombreapp = new javax.swing.JLabel();
        homefondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir.png"))); // NOI18N
        btnsalir.setText("Salir de la cuenta");
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 150, -1));

        btnactividadesrecientes.setText("Actividades Recientes");
        btnactividadesrecientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnactividadesrecientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 190, -1));

        btnsaldoactual.setText("Saldo Actual");
        btnsaldoactual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsaldoactual.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel1.add(btnsaldoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 50));

        btncomprar.setText("Comprar");
        btncomprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncomprar.setMaximumSize(new java.awt.Dimension(80, 23));
        btncomprar.setMinimumSize(new java.awt.Dimension(80, 23));
        btncomprar.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel1.add(btncomprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 110, 50));

        btninfocuenta.setText("Info.Cuenta");
        btninfocuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btninfocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 50));

        btntransferir.setText("Transferir");
        btntransferir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btntransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 110, 50));

        anuncios.setEditable(false);
        jPanel1.add(anuncios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, 50));

        nombreapp.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        nombreapp.setForeground(new java.awt.Color(255, 255, 255));
        nombreapp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreapp.setText("PLF");
        jPanel1.add(nombreapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, 40));

        homefondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Home.png"))); // NOI18N
        jPanel1.add(homefondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anuncios;
    private javax.swing.JButton btnactividadesrecientes;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btninfocuenta;
    private javax.swing.JButton btnsaldoactual;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btntransferir;
    private javax.swing.JLabel homefondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreapp;
    // End of variables declaration//GEN-END:variables
}
