/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas_banco;

/**
 *
 * @author fvarg
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_de_sesion
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        pass1 = new javax.swing.JPasswordField();
        viewpass = new javax.swing.JTextField();
        viewpass1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        viewusu = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        usuario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        etifondo = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pass1.setText("jPasswordField1");
        jPanel1.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 302, 234, 31));

        viewpass.setEditable(false);
        viewpass.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        viewpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        viewpass.setText("Email");
        viewpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(viewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 234, 31));

        viewpass1.setEditable(false);
        viewpass1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        viewpass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        viewpass1.setText("Contraseña");
        viewpass1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(viewpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 253, 234, 31));

        jButton1.setText("Crear Cuenta");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 230, 50));

        viewusu.setEditable(false);
        viewusu.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        viewusu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        viewusu.setText("Usuario");
        viewusu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewusu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(viewusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 143, 234, 31));

        email.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 234, 28));

        usuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 192, 234, 28));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 44, 250, 40));

        etifondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Fondo1.2.png"))); // NOI18N
        jPanel1.add(etifondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_de_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel etifondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JTextField usuario1;
    private javax.swing.JTextField viewpass;
    private javax.swing.JTextField viewpass1;
    private javax.swing.JTextField viewusu;
    // End of variables declaration//GEN-END:variables
}
